#! /bin/sh

sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor eDP1 -n 0 -d I II III
#bspc monitor HDMI1 -n 1 -d IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer  true
bspc config pointer_follows_monitor true
# bspc config remove_disabled_monitors true
# bspc config remove_unplugged_monitors true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

notify-send "read bspwmrc"
# [ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
# pgrep -x panel > /dev/null || panel &
panel &
