#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        1
bspc config window_gap          0
bspc config normal_border_color "#000000"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer  true
bspc config pointer_follows_monitor true
# bspc config remove_disabled_monitors true
# bspc config remove_unplugged_monitors true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a feh state=floating follow=on

pkill -f panel
$HOME/.scripts/panel/panel.sh

# Set background
feh --bg-fill ~/Pictures/E5Z_1btA.png
