#!/bin/bash
#
# wm independent hotkeys
#

# terminal emulator
super + Return
	urxvt

# program launcher
super + @space
	dmenu_run

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

#
# bspwm hotkeys
#

# quit bspwm normally
super + alt + Escape
	pkill -x panel; bspc quit

# reload bspwm settings
super + alt + r
        pkill -x panel; pkill -x sxhkd; x$HOME/.config/bspwm/bspwmrc

# close and kill
super + {_,shift + }w
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + g
	bspc node -s biggest

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
super + alt + {Left,Down,Up,Right}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {Left,Down,Up,Right}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

#
# Custom bindings
#

# Raise volume with 5%
XF86AudioRaiseVolume
        exec  pactl set-sink-volume @DEFAULT_SINK@ +5%

# Raise volume with 1%
XF86AudioRaiseVolume + shift
        exec pactl set-sink-volume @DEFAULT_SINK@ +1%

# Lower volume with 5%
XF86AudioLowerVolume
        exec pactl set-sink-volume @DEFAULT_SINK@ -5%

# Lower volume with 1%
XF86AudioLowerVolume + shift
        exec pactl set-sink-volume @DEFAULT_SINK@ -1%

# Sound toggle on/off
XF86AudioMute
        exec pactl set-sink-mute @DEFAULT_SINK@ toggle

# Microphone toggle on/off
XF86AudioMicMute
        exec pactl set-source-mute 1 toggle

# increase screen brightness
XF86MonBrightnessUp
        exec xbacklight -inc 5 

# increase small step
XF86MonBrightnessUp + shift
        exec xbacklight -inc 1 

# decrease screen brightness
XF86MonBrightnessDown
        exec xbacklight -dec 5

# decrease small step
XF86MonBrightnessDown + shift
        exec xbacklight -dec 1

# Display toggle between useing external HMDI or not
XF86Display
        exec ~/.scripts/toggleExternalMonitor.sh

XF86Bluetooth
        bspc reload
#        dmenu_run

# # program launcher
# super + @space
# 	dmenu_run


#
# Application shortcuts
#

super + shift + f
      firefox

super + shift + e
      emacsclient -c || emacs
